language: go

arch:
  - amd64
  - arm64


go:
  - 1.9.x
  - 1.10.x
  - master
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     1.15.x;
    fi

install: |
  mkdir -p $HOME/gopath/src/code.cloudfoundry.org/log-cache-cli
  rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/code.cloudfoundry.org/log-cache-cli/
  export TRAVIS_BUILD_DIR=$GOPATH/src/code.cloudfoundry.org/log-cache-cli
  go get -t -d -v code.cloudfoundry.org/log-cache-cli/...

script: go test code.cloudfoundry.org/log-cache-cli/... --race

matrix:
  allow_failures:
  - go: master
