language: go

jobs:
  - arch: amd64
    go:
      - 1.9.x
      - 1.10.x
      - master
  - arch: arm64
    go:
      - 1.15.x

install: |
  mkdir -p $HOME/gopath/src/code.cloudfoundry.org/log-cache-cli
  rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/code.cloudfoundry.org/log-cache-cli/
  export TRAVIS_BUILD_DIR=$GOPATH/src/code.cloudfoundry.org/log-cache-cli
  go get -t -d -v code.cloudfoundry.org/log-cache-cli/...

script: go test code.cloudfoundry.org/log-cache-cli/... --race

matrix:
  allow_failures:
  - go: master
